services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-app
    container_name: chat-app-1
    ports:
      - "8101:8100"
    environment:
      IS_CONTAINER_RUN: true
    depends_on:
      - redis

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-app
    container_name: chat-app-2
    ports:
      - "8102:8100"
    environment:
      IS_CONTAINER_RUN: true
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"